fixtures:
  repositories:
    php: "git://github.com/example42/puppet-php.git"
    timezone: "git://github.com/example42/puppet-timezone.git"
    puppi: "git://github.com/example42/puppi.git"
    newrelic: "git://github.com/fsalum/puppet-newrelic.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    ntp: "git://github.com/puppetlabs/puppetlabs-ntp.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
  symlinks:
    site: "#{source_dir}/site"

